server:
  port: 8010
spring:
  application:
    name: school-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: school-service
      host: localhost
      port: 8500