eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8762
spring:
  application:
    name: zull
  devtools:
    restart:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8763
