eureka: 
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8763
  cloud:
    config:
      url: http://localhost:8764
        
