eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8761
spring:
  application:
    name: service-discovery
  boot:
    admin:
      client:
        url: http://localhost:8763